apiVersion: v1
kind: Service
metadata:
  name: ai-studio
  namespace: tools
  annotations:
    placeholder: "true"
spec:
  type: NodePort
  selector:
    app: ai-studio
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30880
