clusterName: prox-n100
controller:
  ip: 192.168.1.151
workers:
  - 192.168.1.152
  - 192.168.1.153

domain: funoffshore.com

nfs:
  server: 192.168.1.112
  path: /volume1/fire_share2

features:
  monitoring: false
  logging: false
  certManager: false
