clusterName: prox-n100
controller:
  ip: 192.168.1.214

workers:
  - 192.168.1.215
  - 192.168.1.216

domain: funoffshore.com

nfs:
  server: 192.168.1.112
  path: /volume1/fire_share2

features:
  monitoring: false
  logging: false
  certManager: false
