apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-minecraft
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/kubernetes/apps/games/minecraft
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
  targetNamespace: games
  timeout: 5m
  wait: true
  suspend: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-jellyseer
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/kubernetes/apps/media/jellyseer
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
  targetNamespace: media
  timeout: 5m
  wait: true
  suspend: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-ai-studio
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/kubernetes/apps/tools/ai-studio
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
  targetNamespace: tools
  timeout: 5m
  wait: false
  suspend: true  # placeholder until ready to run
